### ISSUE TITLE
주량라벨 데이터 저장 경로

### ISSUE THREAD

**Issue by cbinarycastle** [alcohol-king/sooling-api#25]
@3457soso 
주량라벨 데이터를 저장해야 하는데 어디에 저장해야 될까요,,,?
drink_card 테이블에 주량 컬럼 추가해서 거기에 저장하자니 카드랑 라벨이랑 별개로 보는 게 맞는 것 같고,
user 테이블에 drink_history 테이블처럼 각 주종별로 컬럼 하나씩 추가해서 거기에 저장하자니 이것도 좀 아닌 것 같기도 하고,,,,,,,
ㅠㅠㅠㅠ누나는 어떻게 생각하세요 ??!

**Comment by cbinarycastle** [comment]
주량 라벨 설정 화면:
https://app.zeplin.io/project/5c14bd187eda90245b594ece/screen/5c1f891e7501c0242a5199e9

**Comment by soyoungpark-me** [comment]
어 근데 이거... drink_card도 유저 한 명 당 한 장이고 (소맥와막 각 최대 1장 씩)
주량 라벨 데이터는 drink_card랑 동일하게 하되 보이는 방법만 다르게 하기로 해서...

예를 들면 ... 
drink_card에 소주 설정이 반병/1병/1.5병/2병/3병/4병/5병/무한대 이렇게 될 텐데 

여기서 내가 반병으로 설정했으면 
주량 카드에는 반 병으로 나오고, 주량 라벨 (레벨)은 1이구, 

1병으로 설정했으면
주량 카드에는 한 병으로 나오고, 주량 라벨 (레벨)은 2...

이런식으로 하니까, 라벨 설정 해줄 때도 drink_card 내용 그대로 갖다 쓰믄 되지 않을까유?? 몇 번째 값을 지정했는지(인덱스)가 결국 레벨이어서!

글로 쓰려니 힘들다 . . . 문장력 바닥쓰 . . .

**Comment by cbinarycastle** [comment]
이해 잘돼요 누나ㅋㅋㅋㅋㅋㅋㅋㅋ
근데 카드에는 주량이 적용이 안되지 않아요 ??
빈 칸에 사용자가 직접 텍스트 쓰는 걸로 알고 있어서요,,!!!

**Comment by soyoungpark-me** [comment]
직접 쓰는 것은 주량 기록(캘린더)이고, 프로필 사진용 카드는 선택하는걸로 알고있숩니다!! :+1:

**Comment by cbinarycastle** [comment]
https://app.zeplin.io/project/5c14bd187eda90245b594ece/screen/5c1f891e81415cb006678fe5
여기서 프로필 카드 수정하는거 아닌가요 ??!

**Comment by soyoungpark-me** [comment]
저 **~~~까지는 마시면서** 요 부분은 그냥 저 자체로 텍스트로 쓰는것!
숫자 아니어도 되고...
**술집 부수면서** 마실 수 있어요
이렇게 들어갈 수도 있고..?

내가 말한 선택하는고는
https://app.zeplin.io/project/5c14bd187eda90245b594ece/screen/5c1f891e7501c0242a5199e9
여기서 주량 고르는거!

**Comment by cbinarycastle** [comment]
아아 근데 제가 좀 걸리는 건 만약에 소주 라벨은 등록하고 소주 카드는 등록 안한 상태면 소주 레벨 값만 있고 소주 카드 텍스트 값은 null이 들어가버리는 점이에요 !
사실 그래도 상관은 없지만 뭔가 더 좋은 방법이 없을까,, 해서요ㅠㅠ

**Comment by soyoungpark-me** [comment]
와 근데 그럼... 카드 등록 + 라벨 등록을 한 번에 묶어서...
둘 다 등록해야만 카드가 등록되는 형식으로 바꿔야하남...?

https://app.zeplin.io/project/5c14bd187eda90245b594ece/screen/5c1d114859c181af58991e18

저기 보면 맥주 카드 있고 맥주 라벨 있듯이...
둘이 따로 노는것보다는 맥주 카드 등록할 때 라벨도 같이 등록하든가 아님 말든가 해야할것같은데 

이건... 기획쪽이라 다같이 얘기해봐야할듯싶슴...

**Comment by cbinarycastle** [comment]
맞아요 저두 한 번에 묶는 게 더 일관되고 좋을 것 같은데,,
함 여쭤봐야겠어요 !
근데 언제 만나지 ,,,,,, 그냥 카톡으로 여쭤볼까요 ?!
