### ISSUE TITLE
주종별 레벨 데이터 타입

### ISSUE THREAD

**Issue by cbinarycastle** [alcohol-king/sooling-api#52]
@3457soso 반 병 단위가 있는 주종은 레벨이 소수일텐데 그러면 level 컬럼 데이터 타입을 소수로 해야될까요 ??

**Comment by soyoungpark-me** [comment]
그거 소수점 안만드려고...
일부러 막 잔 수로 단위 바꾸고 그랬심!

https://trello.com/c/V88vfKNt
여기 수지언니가 새로 단위 맞춰서 올려주셔씀!

**Comment by cbinarycastle** [comment]
아 전 오른쪽에 있는 레벨로 저장하는 걸로 착각했어요ㅎㅎㅎ,,
감사합니다 ~~!!!
